### ISSUE TITLE
Why not just use 'u=participants[sub]'?

### ISSUE THREAD

**Issue by YatongChen0603** [Human-Signals-Lab/AudioIMU#2]
https://github.com/Human-Signals-Lab/AudioIMU/blob/c544d1ac863587544862ea28e2c60e371ef41ca5/lab_multimodal_train.py#L117

Thks

**Comment by dawei-liang** [comment]
You are right. Some of the code may not be optimized in organization since we used it for different purposes. Thanks for the comments!
